# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate CFW Config

on:
  push:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        python ./generate_cfw.py   
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@1.0.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: temp_config.yml
        asset_name: RandomC0nfig.yml
        tag: v0.1
        overwrite: true


